### ISSUE TITLE
Windows 10 Security detects trojan

### ISSUE THREAD

**Issue by danialgood** [Mr30nama/30nama-Hybrid#1]
windows 10 security detects **_Wacatac.B!ml_**  trojan

![image](https://user-images.githubusercontent.com/8021394/227400182-76a0b34d-9960-446c-a71a-4ffcfdc6968c.png)

**Comment by EternalC0der** [comment]
Bekhatere copyright, ejazeye sign kardan nemidan,
windows defender ham gir mide behesh.
user ha ziad beshan mifahme safe e
